### ISSUE TITLE
Modify unit tests to check that we're getting a valid sampling of randomness

### ISSUE THREAD

**Issue by scottchiefbaker** [paragonie/random_compat#4] opened 2015-07-07 23:48 UTC
As part of issue #3 we weren't outputting values in the full supplied range (only the lower 80%). I suggest we modify the unit tests to generate 1000 random numbers, and verify that there are values in the lowest 2%, and the highest 98%.

Is there a better way to check that we're getting a true random sample?

**Comment by paragonie-scott** [comment] 2015-07-07 23:50
> Is there a better way to check that we're getting a true random sample?

We could implement the [Diehard tests](https://en.wikipedia.org/wiki/Diehard_tests), I suppose. I'd just hesitate to put this on Travis, since any test can fail randomly and give us a "build: failing" status even when everything works. :)

**Comment by scottchiefbaker** [comment] 2015-07-07 23:53
The Travis "problem" is valid for sure. I'm not sure the best way to address that. Maybe we have local tests that like this which MAY fail in weird random circumstances, but Travis just tests basic functionality?

Since the point of this library is "good" randomness, we should implement some type of unit test to verify that the output is actually "good".

**Comment by paragonie-scott** [comment] 2015-07-07 23:55
> Maybe we have local tests that like this which MAY fail in weird random circumstances, but Travis just tests basic functionality?

We could probably have two test directories, one for basic tests and the other for full statistical analyses. Then modify `tests/phpunit.sh` to accept an argument that switches the full tests on, and then have a `.travis.yml` file that doesn't pass this flag.

**Comment by scottchiefbaker** [comment] 2015-07-07 23:57
From the Diehard tests: "Birthday spacings: Choose random points on a large interval. The spacings between the points should be asymptotically exponentially distributed."

What if we generate 1000 random numbers. Then we count the number that are 0 - 100, 101 - 200, 201 - 300, etc...

Each group should have a roughly similar number. If one of the groupings had a higher or lower number we could fail the test?

**Comment by paragonie-scott** [comment] 2015-07-08 00:10
What do you propose the threshold be? I rarely get failures when I say they must be within 5% of an expected mean.

```php
    public function testBirthday()
    {
        $buckets = array_fill(0, 20, 0);
        for ($i = 0; $i < 100000; ++$i) {
            $random = random_int(0, 999);
            $bucket = (int) floor($random / 100);
            ++$buckets[$bucket];
        }
        for ($i = 0; $i < 10; ++$i) {
            $this->assertTrue(
                $buckets[$i] < 10500 
                    &&
                $buckets[$i] > 9500
            );
        }
    }
```

**Comment by scottchiefbaker** [comment] 2015-07-08 00:28
Oh nice... Generating 100,000 random numbers, and then checking the contents of the buckets gives out a VERY even distribution. In the above example, with ten buckets we expect each bucket should have ~10,000 entries (100,000 / 10 buckets). 

Real world output of the above code gives me a variation of LESS than 2%. 5% seems like it should account for wider variations, without affecting the quality of the test.

**Comment by scottchiefbaker** [comment] 2015-07-08 00:44
I suggest that we use a non power-of-ten for the number of buckets, it's too evenly divisible into things and may mask problems. I modified the above to be tweakable:

```
$num_buckets         = 17;     // Number of buckets to make
$nums_to_generate    = 100000; // Number of rands to make
$buckets             = array_fill(0, $num_buckets, 0);

// The number of ints we expect per bucket +/- 2%;
$expected_per_bucket = floor($nums_to_generate / $num_buckets);

for ($i = 0; $i < $nums_to_generate; $i++) {
	$random = random_int(0, 999);
	$bucket = (int) floor($random / ($nums_to_generate / $num_buckets / 100));
	$buckets[$bucket]++;
}

print "<pre>" . print_r($buckets,1) . "</pre>";
```

**Comment by paragonie-scott** [comment] 2015-07-08 01:12
Set `$nums_to_generate` to 400000 and observe.

**Comment by lt** [comment] 2015-07-08 06:33
It is not the job of this library to test the quality of the underlying RNG. Just saying.

**Comment by paragonie-scott** [comment] 2015-07-08 06:41
@lt True, I could just close this issue and forego the effort of adding granular unit tests. 

Just ensuring that they behave as expected (i,e, if I say `random_int(0,255)` a few million times there shouldn't be a number in that range that is never returned) is probably good enough.

**Comment by lt** [comment] 2015-07-08 07:50
`random_int` actually has an implementation detail that can be tested by mocking `random_bytes` and returning a predictable stream that contains data that should produce unbiased results.

**Comment by paragonie-scott** [comment] 2015-07-08 09:02
That's pretty neat. Do you think the current tests...

* try to cover too much?
* are okay?
* don't cover enough?

**Comment by paragonie-scott** [comment] 2015-07-09 21:51
I think we can close this now. The unit tests as written should catch any regressions. Let me know if it needs to be reopened.

**Closed by paragonie-scott** 2015-07-09 21:51 UTC
