### ISSUE TITLE
mcrypt_create_iv() fails on Windows when env is empty

### ISSUE THREAD

**Issue by nicolas-grekas** [paragonie/random_compat#68] opened 2015-10-19 09:25 UTC
On Windows, the script below displays:
`PHP Warning:  mcrypt_create_iv(): Could not gather sufficient random data in Command line code on line 1`

```php
<?php

$pipes = array();
$env = array();

$p = proc_open('php -r "echo strlen(mcrypt_create_iv(1, MCRYPT_DEV_URANDOM));"', array(1 => array('pipe', 'w')), $pipes, getcwd(), $env);
echo stream_get_contents($pipes[1]), "\n";
proc_terminate($p);

```

The issue disappears when `$env` is set to `null`.

**Comment by oittaa** [comment] 2015-10-19 11:44
As the documentation says (https://secure.php.net/manual/en/function.proc-open.php):
>  env
>    An array with the environment variables for the command that will be run, or NULL to use the same environment as the current PHP process

And you are deliberately giving it an empty array. How any of this affects random_bytes_mcrypt.php and what's the problem?

**Comment by nicolas-grekas** [comment] 2015-10-19 11:51
An empty array or any array in fact. This makes random_compat implem fails when php is run in a subprocess, which is quite common at least in e.g. Symfony when running insulated functional tests

**Comment by nicolas-grekas** [comment] 2015-10-19 13:43
Well, after investigating a bit more the issue:
- PHP7 is also affected by the issue, but it throws an `Exception` instead of a warning, so I think error handling should be enhanced
- adding the `SYSTEMROOT` env variable removes the warning/exception so this one is mandatory for `CryptGenRandom()`

**Comment by paragonie-scott** [comment] 2015-10-19 14:05
Okay, what can we do differently in random_bytes_mcrypt.php so it doesn't fail in a sub-process? Changing how the sub-process is created/used is out of scope for our library, after all.

**Comment by oittaa** [comment] 2015-10-19 14:10
I created a quick pull request #69, which tests Mcrypt functionality before including the PHP file. Could someone with a Windows machine test and check if it works as intended?

**Comment by nicolas-grekas** [comment] 2015-10-19 14:11
given PHP7 has almost the same behavior, adding an `@` in front of `mcrypt_create_iv` could be enough

**Comment by AshleyPinner** [comment] 2015-10-19 14:13
Since you don't tell the invocation where system root is, `NTE_PROV_DLL_NOT_FOUND`/`NTE_PROVIDER_DLL_FAIL` are the most likely return codes when PHP tries to invoke `CryptAcquireContext()`. I'd be tempted to lean on this as a PHP bug, as PHP should try to recover from this situation, but the code only looks for success, rather than handling failures.

**Comment by nicolas-grekas** [comment] 2015-10-19 14:56
PHP bug reported, let's see what's next there:
https://bugs.php.net/70742

**Comment by AshleyPinner** [comment] 2015-10-19 15:02
Might be worth including a test case and error message that match each other ;)

**Comment by paragonie-scott** [comment] 2015-10-20 15:01
@nicolas-grekas Is this resolved on Symfony's end, or do we still need to consider making changes to random_compat to prevent this failure?

**Comment by nicolas-grekas** [comment] 2015-10-20 15:15
Given the feedback in https://bugs.php.net/70742, adding an `@` in front of `mcrypt_create_iv` is enough to close this issue IMHO.

**Comment by paragonie-scott** [comment] 2015-10-20 15:23
https://github.com/paragonie/random_compat/commit/56d0b470ce42c18da7d7c4dd00b27d99f83d5d4b

**Closed by paragonie-scott** 2015-10-20 15:23 UTC
